apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-subscriber-binding
  namespace: testops-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator-role
subjects:
  - kind: ServiceAccount
    name: engine-subscriber-sa
    namespace: testops-engine
